### ISSUE TITLE
Add Threadpool support

### ISSUE THREAD

**Issue by hcw70** [juangburgos/QDeferred#5]
I was trying to use this library as a replacement for QtConcurrent.
However, that there needs to be a worker per job, and a thread per work, means that i cant easily launch the same job several times concurrently.

Is it possible to add something like a thread pool from which the worker gets a free thread upon activation?

**Comment by juangburgos** [comment]
Thank you for your interest, if your use case is launching the same job several times concurrently, then [it is still recommended to use QtConcurrent](https://github.com/juangburgos/QDeferred#conclusion-and-recommendations). 

`QLambdaThreadWorker` is not designed for that specific use case, that being said, you can still pass around `QDeferred` objects to notify results across `QThreads` (since `QDeferred` is thread-safe).

**Comment by hcw70** [comment]
@juangburgos Thanks for the information. Yes, my intent was to run the same Job (class) concurrently, but each Job Instance should handle its own thread. So i was trying to put the worker into a class member and failed because of compiler errors i did not really understand (and so was not able to fix it).

If that is intented that the worker can / should not be part of the instance, i am fine with that.
